### ISSUE TITLE
All requests to prerender.io use the NING 1.0 User Agent

### ISSUE THREAD

**Issue by jdulberger** [Rhinofly/play-prerender#2]
All requests to prerender.io from Rhiofly play-prerender use the "NING 1/0" User Agent. Prevents us from seeing the bot's "true" user agent.
A test case is that I'm crawling our page with this:
curl -H"User-Agent: googlebot" http://www.mypage.com/somewhere
and while Rhinofly play-prerender recognizes this correctly it doesn't forward the matched googlebot string on to Rhinofly. Not causing an issues at the moment, just a nice to have.
I'd be willing to contribute a pull request to add that feature.

**Comment by EECOLOR** [comment]
Closing in favor of #3
