### ISSUE TITLE
Initial request response headers contain the `X-Prerender-Token`

### ISSUE THREAD

**Issue by Hayena** [Rhinofly/play-prerender#5]

**Comment by EECOLOR** [comment]
Can you descrine the problem more clearly? I fear I do not understand what you mean

**Comment by klaasman** [comment]
Let me descrine the problem: the `X-Prerender-Token` shouldn't be a response header on the index page.

**Comment by EECOLOR** [comment]
So this header is not required anymore for prerender?

**Comment by klaasman** [comment]
not as response header on the index page
